### ISSUE TITLE
Could you please share the annotation files of J-HMDB for testing?

### ISSUE THREAD

**Issue by ilovecv** [dzh19990407/LBDT#3]
Hi,

Great work! May I know how to test the model on J-HMDB dataset? For A2D and Youtube-vos, the annotation files are provided. I am wondering if you can also share the annotation file for J-HMDB dataset, so I can test the model on it. Thanks!

**Comment by dzh19990407** [comment]
Thanks for your attention to our work! Unfortunately, I can't get the annotation file for J-HMDB dataset from our servers since I'm not at school right now. You can prepare the annotation file by yourself with the 'test.txt' provided in https://github.com/haowang1992/ACGA#:~:text=Split%20(BaiduNetDisk%2C%20OneDrive%20passed%3A%20p0ak). I will provided our annotation file as soon as I can get access to the servers' data.

**Comment by ilovecv** [comment]
@dzh19990407 Thank you very much for your quick reply. Looking forward to it.

**Comment by dzh19990407** [comment]
We have upload the annotation file of J-HMDB dataset to the same google drive link as A2D dataset.
